#----------------PROPIEDADES--------------------------------------------------------------------------
systemProp.serenity.project.name=Automation Testing - Project
systemProp.gradle.props.project.encode=UTF-8
systemProp.gradle.props.resource.encode=utf8
systemProp.gradle.props.project.package.base=com.arreglatech.project
systemProp.gradle.props.project.package.java.test.url=src/test/java
systemProp.gradle.props.project.package.java.main.url=src/main/java
systemProp.gradle.props.project.package.resource.test.url=src/test/resources

#reports
systemProp.gradle.props.project.reports.dir=build/reports
systemProp.gradle.props.project.reports.dir.history=history
systemProp.gradle.props.project.reports.recents.limit=5

#----------------BUILD REUSE WITH DEPENDENCY-------------------------------------
group=com.arreglatech.project
version=1.0-SNAPSHOT
#----------------PERFORMANCE GRADLE-------------------------------------------------------------------
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondeman=true
org.gradle.caching=true
#----------------JAVA---------------------------------------------------------------------------------
javaVersion=17
#----------------DEPENDENCIES----------------------------------------------------
#https://plugins.gradle.org/plugin/net.serenity-bdd.serenity-gradle-plugin
#https://github.com/serenity-bdd/serenity-core#what-is-the-latest-stable-version-i-should-use
serenityVersion=4.2.30

#JUnit5
junit_platform_launcher_version=1.11.4
cucumber_junit_platform_engine_version=7.20.1
junit_platform_suite_version=1.11.4
junit_jupiter_engine_version=5.11.4

logback_classic_version=1.5.17
assertj_core_version=3.24.2

#Utils/Tools
lombokVersion=1.18.30