serenity.test.root= com.arreglatech.project.runners
serenity.project.name= structure automation testing with selenium, testng, serenitybdd and cucumber By Arreglatech
report.tagtypes=capability,feature
report.customfields.environment=Quality Assurance
report.customfields.ApplicationVersion=1.0.0
report.customfields.user=User
report.customfields.squad=Squad
report.customfields.order=ApplicationVersion,environment,user,squad
