serenity.test.root= com.arreglatech.project.runners
serenity.project.name= structure automation testing with selenium, testng, serenitybdd and cucumber By Arreglatech
report.tagtypes=capability,feature
report.customfields.environment=Quality Assurance
report.customfields.ApplicationVersion=1.0.0
report.customfields.user=User
report.customfields.squad=Squad
report.customfields.order=ApplicationVersion,environment,user,squad

webdriver.driver=chrome
webdriver.chrome.driver=src/test/resources/drivers/chromedriver.exe

chrome.switches=--start-maximized

webdriver.timeouts.implicitlywait = 80000
serenity.take.screenshots=AFTER_EACH_STEP
serenity.verbose.steps=FALSE
serenity.report.encoding=UTF8
